site_name: SASP. U5. Plans de sostenibilitat en empreses TIC

theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'green'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      baselevel: 2
      toc_depth: 3
      title: Continguts


plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.


nav:
  - "Inici": 'index.md'
  - "Què és un pla de sostenibilitat? Estructura i fases" : '1.pla_sostenibilitat.md'
  - "Identificació de grups d'interès en entorns TIC" : '2.grups_interes.md'
  - "Mesura del rendiment sostenible (KPIs, informes, ISO 14001": '3.mesura_rendiment.md'
  - "Estudi de casos reals": '4.exemples.md'
  

