site_name: Sostenibilitat aplicada al sistema productiu

theme: 
  name: material
  palette:
    primary: 'deep purple'

markdown_extensions:
  - def_list

plugins:
  - search

nav:
  - "RA1 i RA2  (Pilar Millàs)": 'ra1_2.md'
  - "RA  i RA5 (Tamara Romero)": 'ra4_5.md'
  - "RA3 i RA6. (Àlex Benet)": 'ra3_6.md'
  - "Tasca Final": 'tasca_final.md'