site_name: SASP. U3. Els ODS en el disseny i ús de tecnologies

theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'green'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      baselevel: 2
      toc_depth: 3
      title: Continguts


plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.


nav:
  - "Inici": 'index.md'
  - "Els ODS rellevants per al sector TIC": '1.ods_rellevants.md'
  - "Disseny de software i aplicacions amb criteris ètics i sostenibles": '2.disseny_sw.md'
  - "TIC i impacte positiu: accessibilitat, educació, salut, participació": '3.impacte_positiu.md'
