site_name: Sostenibilitat Aplicada al Sector Productiu de les TIC

theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'green'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      baselevel: 2
      toc_depth: 3
      title: Continguts


plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.


nav:
  - "Inici": 'index.md'
  - "1. Què és la sostenibilitat i per què importa en les TIC?" : '1.sostenibilitat_tic.md'
  - "2. Marcs internacionals per al desenvolupament sostenible" : '2.marcs_internacionals.md'
  - "3. Els aspectes ASG (Ambientals, Socials i de Governança) en empreses TIC" : '3.asg.md'
  - "4. L'impacte de les TIC sobre el planeta" : '4.impacte.md'
  - "5. Mesurar l'impacte ambiental en TIC" : '5.mesura_impacte.md'
  - "6. Introducció a les accions de millora i compensació" : '6.accions.md'