site_name: SASP. U2. Reptes ambientals i socials del sector TIC

theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'green'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      baselevel: 2
      toc_depth: 3
      title: Continguts


plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.


nav:
  - "Inici": 'index.md'
  - "1. Consum energètic dels equips, CPDs i xarxes": '1.consum_energetic.md'
  - "2. Residus electrònics (e-waste): impactes i regulació": '2.residus.md'
  - "3. Bretxa digital i desigualtats socials en l'accés i ús de la tecnologia": '3.bretxa_digital.md'
  - "4. Ciberètica, drets digitals i sostenibilitat": '4.ciberetica.md'
  - "5. Mesura i regulació dels impactes socials i ambientals en les TIC": '5.mesura.md'
